name: PAM
favicon: null
layout_spectrum: 0.030385198770090938
typography_spectrum: 0.19864930980838835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7373850720468909
  lightness: 0.2180495501961559
  saturation: 0.598451194819063
  rhythmicContrast: 0.5322977700270712
purpose: []
